apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlOREF5TWpBdwpOekl4TURaYUZ3MDBOREF5TWpBd056SXhNRFphTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFER2I0dmpqdUhrVjFhNHkxZURJd21LWmh1SUxOa254cmhscDFybThmcC8rVzdrTUkrOQowWExKNDJJOTBwL3U4U0xMYXpYbm1VT3M4cTZ0V043cDFqbTFJTjRuamhycEJVQWlCdWhvS1JZME92aFNBZmFWClZCYUV1QzIvd0wvYW5Yd2R3ZHFMczh5MHM5L0ViUnZ1V2RTS1ZVVnBKWWMzbDdyNDVyMGVtSEtobStKZWhCMnIKeFRzQmtibzRaZ2MwZDkwWTI3MGcyeHNLRUY2VWJxUDZzeVQzUEdGK3RJSTY4QXBaVGVaZFgyZ2dVSzlpdFBCNApocHFJQ1F5dlkzcnd5ZmtNRTR3VjBEV011T0xtcmxlSUlRNE0zYm1mWkQ3dFJmR0ZxbUJTSURtdkY2b213TDh5CkJVMWV5NlQ1ajFKQzdFYjNnck80bW0xekwrcUo0YXlqai94ZkFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlJrbmlRR1BnVXNCMHFJUWZGdwpFZzZ0QlBvSklUQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFpdHZ5TUZzdENOZURQN3pnNXRKT21zd0lzcFhzCk1nZDdCVDd0MHhmeHZZTGlCUDd3a0J2NGlSK25LSjJJa1hvTSt2OFQ3WTNObVYvK3daa0pQbVJ0RnJDZUNFN0UKZGVlbVduWW94dG1BelRHM2dDMDZpZjZEZ0dvK3hLSXhQOCtRVGZTZytlYTdNQWREdkVtdG5jVXp0bEZoTHV5QQprS3hIK2wwMUxHVU84aks3cXBTa1pHTFNFUzlNZGhkb0ZoNlE4SUYwYjVNQ0R1dUc2dVZaS2xuakVvWnFiVlpICklxRlJtT0I3N2dTa3JRTUI3bWgvT2xKRVZVMEJMakhJMzZUamV5YmxkakVtZGhCd3NvaHhhelM0NmJiWERCZUcKakR4Zmt4K09TS3UyV3BZdzdzZkpPeVJEdHVJbmJ5L0k2Y29XTEcvV3N0S1YrSEs0aU9JeXNMeWZyZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://83671074-f7f2-4bd0-8a7f-a2abbe0526f5.k8s.ondigitalocean.com
  name: do-fra1-training-demo-k8s
contexts:
- context:
    cluster: do-fra1-training-demo-k8s
    user: do-fra1-training-demo-k8s-admin
  name: do-fra1-training-demo-k8s
current-context: do-fra1-training-demo-k8s
users:
- name: do-fra1-training-demo-k8s-admin
  user:
    token: dop_v1_1cfcd52ce38c076d4c22a8473548cdf3205f0054f498f2e3b49dc6ae548c967a
