replicaCount: 1

image:
  repository: ghcr.io/vojtechmares/kubernetes-training/apps/hello-world
  tag: latest

imagePullSecrets: {}

ingress:
  enabled: true
  host: helm.demo.ddash.cz
  className: nginx
  path: /
  pathType: Prefix
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod

service:
  port:
    name: http
    number: 8080

resources: {}
